//! `hex::workers` — the registry of typed Rust workers hosted by the harness.
//!
//! Each submodule defines one worker via `pub fn worker() -> Worker`. The
//! `registry()` function returns them all; the harness runtime registers
//! each worker's `(TriggerSpec, Handler)` pairs with iii at startup.

pub mod e2e;

// Generated by build.rs: per *.worker.rs `#[path] pub mod <ident>;` +
// `module_registry()` + `module_paths()`.
pub mod hex_modules {
    include!(concat!(env!("OUT_DIR"), "/hex_modules.rs"));
}

use crate::worker::Worker;

/// Return all workers hosted by the hex harness.
///
/// The test-only `hex-e2e` worker is appended ONLY when `HEX_HARNESS_E2E=1`
/// (set by the harness-e2e container) — it never registers in a real deployment.
pub fn registry() -> Vec<Worker> {
    let mut workers = hex_modules::module_registry();
    if std::env::var("HEX_HARNESS_E2E").as_deref() == Ok("1") {
        workers.push(e2e::worker());
    }
    let mut seen = std::collections::BTreeSet::new();
    for w in &workers {
        assert!(
            seen.insert(w.name.clone()),
            "hex registry: duplicate worker name '{}'",
            w.name
        );
    }
    workers
}

#[cfg(test)]
mod tests {
    use super::*;
    use super::hex_modules;
    use crate::worker::TriggerSpec;

    fn cron_exprs(w: &Worker) -> Vec<String> {
        w.handlers
            .iter()
            .filter_map(|(spec, _)| match spec {
                TriggerSpec::Cron { expression } => Some(expression.clone()),
                _ => None,
            })
            .collect()
    }

    #[test]
    fn registry_includes_memory_maintenance_and_backup() {
        let reg = registry();
        let names: Vec<&str> = reg.iter().map(|w| w.name.as_str()).collect();
        assert!(names.contains(&"hex-memory-maintenance"));
        assert!(names.contains(&"hex-backup"));
    }

    #[test]
    fn memory_maintenance_cron_matches_yaml() {
        let reg = registry();
        let mm = reg
            .iter()
            .find(|w| w.name == "hex-memory-maintenance")
            .expect("hex-memory-maintenance present");
        let exprs = cron_exprs(mm);
        assert!(exprs.iter().any(|e| e == hex_modules::memory_maintenance::CRON_INDEX));
        assert!(exprs
            .iter()
            .any(|e| e == hex_modules::memory_maintenance::CRON_CONSOLIDATE_FULL));
    }

    #[test]
    fn memory_maintenance_registers_quick_and_parse_transcripts_crons() {
        // Phase A additive redesign: the worker must also register cron jobs
        // for `hex memory consolidate quick` and `hex memory parse-transcripts`,
        // both on a 15-minute cadence.
        let reg = registry();
        let mm = reg
            .iter()
            .find(|w| w.name == "hex-memory-maintenance")
            .expect("hex-memory-maintenance present");
        let exprs = cron_exprs(mm);

        // The quick-consolidate cron must be registered with a 15-min cadence.
        assert!(
            exprs.iter().any(|e| e == hex_modules::memory_maintenance::CRON_CONSOLIDATE_QUICK),
            "expected CRON_CONSOLIDATE_QUICK to be registered, got crons: {:?}",
            exprs
        );
        assert_eq!(
            hex_modules::memory_maintenance::CRON_CONSOLIDATE_QUICK,
            "0 5,20,35,50 * * * * *",
            "quick-consolidate must run 4x/hour OFFSET from :00 — a quick tick \
             on the :00 boundary lock-skipped the 03:00:00Z full run (2026-06-10)"
        );
        assert_eq!(
            hex_modules::memory_maintenance::ARGV_CONSOLIDATE_QUICK,
            &["hex", "memory", "consolidate", "quick"],
        );

        // The parse-transcripts cron must be registered with a 15-min cadence.
        assert!(
            exprs.iter().any(|e| e == hex_modules::memory_maintenance::CRON_PARSE_TRANSCRIPTS),
            "expected CRON_PARSE_TRANSCRIPTS to be registered, got crons: {:?}",
            exprs
        );
        assert_eq!(
            hex_modules::memory_maintenance::CRON_PARSE_TRANSCRIPTS,
            "0 */15 * * * * *",
            "parse-transcripts must run every 15 minutes"
        );
        assert_eq!(
            hex_modules::memory_maintenance::ARGV_PARSE_TRANSCRIPTS,
            &["hex", "memory", "parse-transcripts"],
        );
    }

    #[test]
    fn backup_is_cron_worker() {
        let reg = registry();
        let bk = reg
            .iter()
            .find(|w| w.name == "hex-backup")
            .expect("hex-backup present");
        assert!(!cron_exprs(bk).is_empty());
    }

    #[test]
    fn registry_includes_generated_module_registry() {
        // The generated module_registry() is a source of workers in registry().
        let gen = hex_modules::module_registry();
        let reg = registry();
        for w in &gen {
            assert!(
                reg.iter().any(|r| r.name == w.name),
                "registry() must include generated module '{}'",
                w.name
            );
        }
    }

    #[test]
    fn registry_names_are_unique() {
        let reg = registry();
        let mut seen = std::collections::BTreeSet::new();
        for w in &reg {
            assert!(seen.insert(w.name.clone()), "duplicate worker name: {}", w.name);
        }
    }
}
